---
title:  "E_MTAB_2805"
author: "Imad Abugessaisa"
date:   "Jun 05, 2019"
output: html_document
---

```{r echo=FALSE}
options(width=100)
knitr::opts_knit$set(verbose = TRUE)
```

## Perform apoptosis analysis on E_MTAB_2805

```{r cars}
library(dplyr)
library(Rmisc)
library(ggplot2)
library(knitr)
library(reshape2)
```

Summary
-------
## extract the FPKM table E_MTAB_2805_FPKM_mereged_Apoptosis_genes
The 'E_MTAB_2805_FPKM_mereged_Apoptosis_genes' table was gerangray

``` {r reshap and matrix formtting}
E_MTAB_2805Coverage_means_DF_melted  <-  melt(E_MTAB_2805Coverage_means_DF,id=c("Annotation"))

## reanme annoation column values
E_MTAB_2805Coverage_means_DF_melted[1:2880,1] <- "E-MTAB-2805"

```

## Plotting of the mean coveage graph
```{r plotting}
E_MTAB_2805Coverage_means_DF_melted_tgc <-
  summarySE(E_MTAB_2805Coverage_means_DF_melted,measurevar = "value",groupvars =c("Annotation","variable"))
E_MTAB_2805Coverage_means_DF_melted_pd <-
 # position_dodge(0.1) # move them .05 to the left and right
png(filename = "./E-MTAB-2805_mean_cov.png",width = 400,height = 400,res = 70)
 meanPlot <- ggplot(E_MTAB_2805Coverage_means_DF_melted_tgc, aes(x=variable, y=value)) +
  geom_errorbar(aes(ymin=value-ci, ymax=value+ci)) +
  geom_line(aes(group=Annotation)) 
meanPlot =meanPlot+ geom_point(aes(group=1), size=2, shape=21, fill="white") + 
  scale_x_discrete(labels  = c(10, 20,30,40,50,60,70,80,90,100)) + 
  labs(x= "μ of the gene body percentile (5'-> 3')") + 
  labs(y= "Gene coverage")+
  labs(title ="mES | E-MTAB-2805 | SMARTer")
meanPlot =meanPlot+ theme(plot.title = element_text(face = "bold", colour="black", size = 20,margin=margin(0,0,3,0))) 
meanPlot =meanPlot+ theme(axis.ticks = element_line(colour = 'black',size = 1.2,linetype = 'dashed'))
meanPlot =meanPlot+ theme(axis.ticks.length=unit(.2, "cm"))
meanPlot =meanPlot+ theme(axis.title.x = element_text(face="bold", colour="black", size=18,family = "Times")) 
meanPlot =meanPlot+ theme(axis.title.y = element_text(face = "bold", colour="black", size=18,family = "Times"))
meanPlot =meanPlot+ theme(legend.position="none")
meanPlot =meanPlot+ theme(axis.text = element_text(face = "bold", colour="black", size=18)) 
meanPlot =meanPlot+ theme(panel.border  = element_rect(colour = "black",fill = NA,size = 2.2),panel.background = element_rect(fill = NA))
meanPlot =meanPlot+ theme(plot.title = element_text(hjust = 0.5))

meanPlot
dev.off()
```


```{r plot full coverage}
pdf(
  "./E-MTAB-2805_full_cov.pdf")
  x = 1:100
 
   color=rgb(0,0,0,alpha=0.25) 
   par(mai=c(0.82,0.82,0.41,0.12))
    plot(
  x,
  ERR580012,col.axis="black",font.axis=2,
  type = 'l',col= color,
 main = list("mES | E-MTAB-2805 | SMARTer",cex=1.5,col = "black",font=2),
 ylab = list("Gene coverage", col = "black",cex=1.5,font=2),
 xlab = list("Gene body percentile (5'-> 3')", col = "black",cex=1.5,font=2),
 col.main = "blue",cex.lab=3,font.lab=2)
lines(x,ERR580013,type='l',col= color)
lines(x,ERR580014,type='l',col= color)
lines(x,ERR580015,type='l',col= color)
lines(x,ERR580016,type='l',col= color)
lines(x,ERR580017,type='l',col= color)
lines(x,ERR580018,type='l',col= color)
lines(x,ERR580019,type='l',col= color)
lines(x,ERR580020,type='l',col= color)
lines(x,ERR580021,type='l',col= color)
lines(x,ERR580022,type='l',col= color)
lines(x,ERR580023,type='l',col= color)
lines(x,ERR580024,type='l',col= color)
lines(x,ERR580025,type='l',col= color)
lines(x,ERR580026,type='l',col= color)
lines(x,ERR580027,type='l',col= color)
lines(x,ERR580028,type='l',col= color)
lines(x,ERR580029,type='l',col= color)
lines(x,ERR580030,type='l',col= color)
lines(x,ERR580031,type='l',col= color)
lines(x,ERR580032,type='l',col= color)
lines(x,ERR580033,type='l',col= color)
lines(x,ERR580034,type='l',col= color)
lines(x,ERR580035,type='l',col= color)
lines(x,ERR580036,type='l',col= color)
lines(x,ERR580037,type='l',col= color)
lines(x,ERR580038,type='l',col= color)
lines(x,ERR580039,type='l',col= color)
lines(x,ERR580040,type='l',col= color)
lines(x,ERR580041,type='l',col= color)
lines(x,ERR580042,type='l',col= color)
lines(x,ERR580043,type='l',col= color)
lines(x,ERR580044,type='l',col= color)
lines(x,ERR580045,type='l',col= color)
lines(x,ERR580046,type='l',col= color)
lines(x,ERR580047,type='l',col= color)
lines(x,ERR580048,type='l',col= color)
lines(x,ERR580049,type='l',col= color)
lines(x,ERR580050,type='l',col= color)
lines(x,ERR580051,type='l',col= color)
lines(x,ERR580052,type='l',col= color)
lines(x,ERR580053,type='l',col= color)
lines(x,ERR580054,type='l',col= color)
lines(x,ERR580055,type='l',col= color)
lines(x,ERR580056,type='l',col= color)
lines(x,ERR580057,type='l',col= color)
lines(x,ERR580058,type='l',col= color)
lines(x,ERR580059,type='l',col= color)
lines(x,ERR580060,type='l',col= color)
lines(x,ERR580061,type='l',col= color)
lines(x,ERR580062,type='l',col= color)
lines(x,ERR580063,type='l',col= color)
lines(x,ERR580064,type='l',col= color)
lines(x,ERR580065,type='l',col= color)
lines(x,ERR580066,type='l',col= color)
lines(x,ERR580067,type='l',col= color)
lines(x,ERR580068,type='l',col= color)
lines(x,ERR580069,type='l',col= color)
lines(x,ERR580070,type='l',col= color)
lines(x,ERR580071,type='l',col= color)
lines(x,ERR580072,type='l',col= color)
lines(x,ERR580073,type='l',col= color)
lines(x,ERR580074,type='l',col= color)
lines(x,ERR580075,type='l',col= color)
lines(x,ERR580076,type='l',col= color)
lines(x,ERR580077,type='l',col= color)
lines(x,ERR580078,type='l',col= color)
lines(x,ERR580079,type='l',col= color)
lines(x,ERR580080,type='l',col= color)
lines(x,ERR580081,type='l',col= color)
lines(x,ERR580082,type='l',col= color)
lines(x,ERR580083,type='l',col= color)
lines(x,ERR580084,type='l',col= color)
lines(x,ERR580085,type='l',col= color)
lines(x,ERR580086,type='l',col= color)
lines(x,ERR580087,type='l',col= color)
lines(x,ERR580088,type='l',col= color)
lines(x,ERR580089,type='l',col= color)
lines(x,ERR580090,type='l',col= color)
lines(x,ERR580091,type='l',col= color)
lines(x,ERR580092,type='l',col= color)
lines(x,ERR580093,type='l',col= color)
lines(x,ERR580094,type='l',col= color)
lines(x,ERR580095,type='l',col= color)
lines(x,ERR580096,type='l',col= color)
lines(x,ERR580097,type='l',col= color)
lines(x,ERR580098,type='l',col= color)
lines(x,ERR580099,type='l',col= color)
lines(x,ERR580100,type='l',col= color)
lines(x,ERR580101,type='l',col= color)
lines(x,ERR580102,type='l',col= color)
lines(x,ERR580103,type='l',col= color)
lines(x,ERR580104,type='l',col= color)
lines(x,ERR580105,type='l',col= color)
lines(x,ERR580106,type='l',col= color)
lines(x,ERR580107,type='l',col= color)
lines(x,ERR580108,type='l',col= color)
lines(x,ERR580109,type='l',col= color)
lines(x,ERR580110,type='l',col= color)
lines(x,ERR580111,type='l',col= color)
lines(x,ERR580112,type='l',col= color)
lines(x,ERR580113,type='l',col= color)
lines(x,ERR580114,type='l',col= color)
lines(x,ERR580115,type='l',col= color)
lines(x,ERR580116,type='l',col= color)
lines(x,ERR580117,type='l',col= color)
lines(x,ERR580118,type='l',col= color)
lines(x,ERR580119,type='l',col= color)
lines(x,ERR580120,type='l',col= color)
lines(x,ERR580121,type='l',col= color)
lines(x,ERR580122,type='l',col= color)
lines(x,ERR580123,type='l',col= color)
lines(x,ERR580124,type='l',col= color)
lines(x,ERR580125,type='l',col= color)
lines(x,ERR580126,type='l',col= color)
lines(x,ERR580127,type='l',col= color)
lines(x,ERR580128,type='l',col= color)
lines(x,ERR580129,type='l',col= color)
lines(x,ERR580130,type='l',col= color)
lines(x,ERR580131,type='l',col= color)
lines(x,ERR580132,type='l',col= color)
lines(x,ERR580133,type='l',col= color)
lines(x,ERR580134,type='l',col= color)
lines(x,ERR580135,type='l',col= color)
lines(x,ERR580136,type='l',col= color)
lines(x,ERR580137,type='l',col= color)
lines(x,ERR580138,type='l',col= color)
lines(x,ERR580139,type='l',col= color)
lines(x,ERR580140,type='l',col= color)
lines(x,ERR580141,type='l',col= color)
lines(x,ERR580142,type='l',col= color)
lines(x,ERR580143,type='l',col= color)
lines(x,ERR580144,type='l',col= color)
lines(x,ERR580145,type='l',col= color)
lines(x,ERR580146,type='l',col= color)
lines(x,ERR580147,type='l',col= color)
lines(x,ERR580148,type='l',col= color)
lines(x,ERR580149,type='l',col= color)
lines(x,ERR580150,type='l',col= color)
lines(x,ERR580151,type='l',col= color)
lines(x,ERR580152,type='l',col= color)
lines(x,ERR580153,type='l',col= color)
lines(x,ERR580154,type='l',col= color)
lines(x,ERR580155,type='l',col= color)
lines(x,ERR580156,type='l',col= color)
lines(x,ERR580157,type='l',col= color)
lines(x,ERR580158,type='l',col= color)
lines(x,ERR580159,type='l',col= color)
lines(x,ERR580160,type='l',col= color)
lines(x,ERR580161,type='l',col= color)
lines(x,ERR580162,type='l',col= color)
lines(x,ERR580163,type='l',col= color)
lines(x,ERR580164,type='l',col= color)
lines(x,ERR580165,type='l',col= color)
lines(x,ERR580166,type='l',col= color)
lines(x,ERR580167,type='l',col= color)
lines(x,ERR580168,type='l',col= color)
lines(x,ERR580169,type='l',col= color)
lines(x,ERR580170,type='l',col= color)
lines(x,ERR580171,type='l',col= color)
lines(x,ERR580172,type='l',col= color)
lines(x,ERR580173,type='l',col= color)
lines(x,ERR580174,type='l',col= color)
lines(x,ERR580175,type='l',col= color)
lines(x,ERR580176,type='l',col= color)
lines(x,ERR580177,type='l',col= color)
lines(x,ERR580178,type='l',col= color)
lines(x,ERR580179,type='l',col= color)
lines(x,ERR580180,type='l',col= color)
lines(x,ERR580181,type='l',col= color)
lines(x,ERR580182,type='l',col= color)
lines(x,ERR580183,type='l',col= color)
lines(x,ERR580184,type='l',col= color)
lines(x,ERR580185,type='l',col= color)
lines(x,ERR580186,type='l',col= color)
lines(x,ERR580187,type='l',col= color)
lines(x,ERR580188,type='l',col= color)
lines(x,ERR580189,type='l',col= color)
lines(x,ERR580190,type='l',col= color)
lines(x,ERR580191,type='l',col= color)
lines(x,ERR580192,type='l',col= color)
lines(x,ERR580193,type='l',col= color)
lines(x,ERR580194,type='l',col= color)
lines(x,ERR580195,type='l',col= color)
lines(x,ERR580196,type='l',col= color)
lines(x,ERR580197,type='l',col= color)
lines(x,ERR580198,type='l',col= color)
lines(x,ERR580199,type='l',col= color)
lines(x,ERR580200,type='l',col= color)
lines(x,ERR580201,type='l',col= color)
lines(x,ERR580202,type='l',col= color)
lines(x,ERR580203,type='l',col= color)
lines(x,ERR580204,type='l',col= color)
lines(x,ERR580205,type='l',col= color)
lines(x,ERR580206,type='l',col= color)
lines(x,ERR580207,type='l',col= color)
lines(x,ERR580208,type='l',col= color)
lines(x,ERR580209,type='l',col= color)
lines(x,ERR580210,type='l',col= color)
lines(x,ERR580211,type='l',col= color)
lines(x,ERR580212,type='l',col= color)
lines(x,ERR580213,type='l',col= color)
lines(x,ERR580214,type='l',col= color)
lines(x,ERR580215,type='l',col= color)
lines(x,ERR580216,type='l',col= color)
lines(x,ERR580217,type='l',col= color)
lines(x,ERR580218,type='l',col= color)
lines(x,ERR580219,type='l',col= color)
lines(x,ERR580220,type='l',col= color)
lines(x,ERR580221,type='l',col= color)
lines(x,ERR580222,type='l',col= color)
lines(x,ERR580223,type='l',col= color)
lines(x,ERR580224,type='l',col= color)
lines(x,ERR580225,type='l',col= color)
lines(x,ERR580226,type='l',col= color)
lines(x,ERR580227,type='l',col= color)
lines(x,ERR580228,type='l',col= color)
lines(x,ERR580229,type='l',col= color)
lines(x,ERR580230,type='l',col= color)
lines(x,ERR580231,type='l',col= color)
lines(x,ERR580232,type='l',col= color)
lines(x,ERR580233,type='l',col= color)
lines(x,ERR580234,type='l',col= color)
lines(x,ERR580235,type='l',col= color)
lines(x,ERR580236,type='l',col= color)
lines(x,ERR580237,type='l',col= color)
lines(x,ERR580238,type='l',col= color)
lines(x,ERR580239,type='l',col= color)
lines(x,ERR580240,type='l',col= color)
lines(x,ERR580241,type='l',col= color)
lines(x,ERR580242,type='l',col= color)
lines(x,ERR580243,type='l',col= color)
lines(x,ERR580244,type='l',col= color)
lines(x,ERR580245,type='l',col= color)
lines(x,ERR580246,type='l',col= color)
lines(x,ERR580247,type='l',col= color)
lines(x,ERR580248,type='l',col= color)
lines(x,ERR580249,type='l',col= color)
lines(x,ERR580250,type='l',col= color)
lines(x,ERR580251,type='l',col= color)
lines(x,ERR580252,type='l',col= color)
lines(x,ERR580253,type='l',col= color)
lines(x,ERR580254,type='l',col= color)
lines(x,ERR580255,type='l',col= color)
lines(x,ERR580256,type='l',col= color)
lines(x,ERR580257,type='l',col= color)
lines(x,ERR580258,type='l',col= color)
lines(x,ERR580259,type='l',col= color)
lines(x,ERR580260,type='l',col= color)
lines(x,ERR580261,type='l',col= color)
lines(x,ERR580262,type='l',col= color)
lines(x,ERR580263,type='l',col= color)
lines(x,ERR580264,type='l',col= color)
lines(x,ERR580265,type='l',col= color)
lines(x,ERR580266,type='l',col= color)
lines(x,ERR580267,type='l',col= color)
lines(x,ERR580268,type='l',col= color)
lines(x,ERR580269,type='l',col= color)
lines(x,ERR580270,type='l',col= color)
lines(x,ERR580271,type='l',col= color)
lines(x,ERR580272,type='l',col= color)
lines(x,ERR580273,type='l',col= color)
lines(x,ERR580274,type='l',col= color)
lines(x,ERR580275,type='l',col= color)
lines(x,ERR580276,type='l',col= color)
lines(x,ERR580277,type='l',col= color)
lines(x,ERR580278,type='l',col= color)
lines(x,ERR580279,type='l',col= color)
lines(x,ERR580280,type='l',col= color)
lines(x,ERR580281,type='l',col= color)
lines(x,ERR580282,type='l',col= color)
lines(x,ERR580283,type='l',col= color)
lines(x,ERR580284,type='l',col= color)
lines(x,ERR580285,type='l',col= color)
lines(x,ERR580286,type='l',col= color)
lines(x,ERR580287,type='l',col= color)
lines(x,ERR580288,type='l',col= color)
lines(x,ERR580289,type='l',col= color)
lines(x,ERR580290,type='l',col= color)
lines(x,ERR580291,type='l',col= color)
lines(x,ERR580292,type='l',col= color)
lines(x,ERR580293,type='l',col= color)
lines(x,ERR580294,type='l',col= color)
lines(x,ERR580295,type='l',col= color)
lines(x,ERR580296,type='l',col= color)
lines(x,ERR580297,type='l',col= color)
lines(x,ERR580298,type='l',col= color)
lines(x,ERR580299,type='l',col= color)

box(lty = "solid", col = 'black',lwd=3)
axis(side=1,lwd=2,lwd.ticks=4,col.ticks="black")
axis(side=2,lwd=3,lwd.ticks=4,col.ticks="black")
dev.off()
```


dev.off()

```

