---
title:  "GSE42268"
author: "Imad Abugessaisa"
date:   "Jun 06, 2019"
output: html_document
---

```{r echo=FALSE}
options(width=100)
knitr::opts_knit$set(verbose = TRUE)
```

## Perform apoptosis analysis on GSE42268

```{r cars}
library(dplyr)
library(Rmisc)
library(ggplot2)
library(knitr)
library(reshape2)
```

Summary
-------

The 'GSE42268_FPKM_mereged_Apoptosis_genes' table was gerangray

``` {r reshap and matrix formtting}
GSE42268Coverage_means_DF_melted  <-  melt(GSE42268Coverage_means_DF,id=c("Annotation"))

## reanme annoation column values
GSE42268Coverage_means_DF_melted[1:770,1] <- "GSE42268"
write.table(GSE42268Coverage_means_DF$Annotation,file = "GSE42268.tsv",sep = "\t",col.names = F,row.names = F,quote = F)

```

## Plotting of the mean coveage graph
```{r plotting}
GSE42268Coverage_means_DF_melted_tgc <-
  summarySE(GSE42268Coverage_means_DF_melted,measurevar = "value",groupvars =c("Annotation","variable"))
GSE42268Coverage_means_DF_melted_pd <-
 # position_dodge(0.1) # move them .05 to the left and right
png(filename = "./GSE42268_mean_cov.png",width = 400,height = 400,res = 70)
 meanPlot <- ggplot(GSE42268Coverage_means_DF_melted_tgc, aes(x=variable, y=value)) +
  geom_errorbar(aes(ymin=value-ci, ymax=value+ci)) +
  geom_line(aes(group=Annotation)) 
meanPlot =meanPlot+ geom_point(aes(group=1), size=2, shape=21, fill="white") + 
  scale_x_discrete(labels  = c(10, 20,30,40,50,60,70,80,90,100)) + 
  labs(x= "μ of the gene body percentile (5'-> 3')") + 
  labs(y= "Gene coverage")+
  labs(title ="mES | GSE42268 | Quartz-seq")
meanPlot =meanPlot+ theme(plot.title = element_text(face = "bold", colour="black", size = 20,margin=margin(0,0,3,0))) 
meanPlot =meanPlot+ theme(axis.ticks = element_line(colour = 'black',size = 1.2,linetype = 'dashed'))
meanPlot =meanPlot+ theme(axis.ticks.length=unit(.2, "cm"))
meanPlot =meanPlot+ theme(axis.title.x = element_text(face="bold", colour="black", size=18,family = "Times")) 
meanPlot =meanPlot+ theme(axis.title.y = element_text(face = "bold", colour="black", size=18,family = "Times"))
meanPlot =meanPlot+ theme(legend.position="none")
meanPlot =meanPlot+ theme(axis.text = element_text(face = "bold", colour="black", size=18)) 
meanPlot =meanPlot+ theme(panel.border  = element_rect(colour = "black",fill = NA,size = 2.2),panel.background = element_rect(fill = NA))
meanPlot =meanPlot+ theme(plot.title = element_text(hjust = 0.5))

meanPlot
dev.off()
```


```{r plot full coverage}
pdf(
  "./GSE42268_full_cov.pdf")
  x = 1:100
 
   color=rgb(0,0,0,alpha=0.25) 
   par(mai=c(0.82,0.82,0.41,0.12))
    plot(
  x,
 SRR616816,col.axis="black",font.axis=2,
  type = 'l',col= color,
 main = list("mES | GSE42268 | Quartz-seq",cex=1.5,col = "black",font=2),
 ylab = list("Gene coverage", col = "black",cex=1.5,font=2),
 xlab = list("Gene body percentile (5'-> 3')", col = "black",cex=1.5,font=2),
 col.main = "blue",cex.lab=3,font.lab=2)
lines(x,SRR616817,type='l',col= color)
lines(x,SRR616818,type='l',col= color)
lines(x,SRR616819,type='l',col= color)
lines(x,SRR616820,type='l',col= color)
lines(x,SRR616821,type='l',col= color)
lines(x,SRR616822,type='l',col= color)
lines(x,SRR616823,type='l',col= color)
lines(x,SRR616824,type='l',col= color)
lines(x,SRR616825,type='l',col= color)
lines(x,SRR616826,type='l',col= color)
lines(x,SRR616827,type='l',col= color)
lines(x,SRR616828,type='l',col= color)
lines(x,SRR616829,type='l',col= color)
lines(x,SRR616830,type='l',col= color)
lines(x,SRR616831,type='l',col= color)
lines(x,SRR616832,type='l',col= color)
lines(x,SRR616833,type='l',col= color)
lines(x,SRR616834,type='l',col= color)
lines(x,SRR616835,type='l',col= color)
lines(x,SRR616836,type='l',col= color)
lines(x,SRR616837,type='l',col= color)
lines(x,SRR616838,type='l',col= color)
lines(x,SRR616839,type='l',col= color)
lines(x,SRR616840,type='l',col= color)
lines(x,SRR616841,type='l',col= color)
lines(x,SRR616842,type='l',col= color)
lines(x,SRR616843,type='l',col= color)
lines(x,SRR616844,type='l',col= color)
lines(x,SRR616845,type='l',col= color)
lines(x,SRR616846,type='l',col= color)
lines(x,SRR616847,type='l',col= color)
lines(x,SRR616848,type='l',col= color)
lines(x,SRR616849,type='l',col= color)
lines(x,SRR616850,type='l',col= color)
lines(x,SRR616851,type='l',col= color)
lines(x,SRR616852,type='l',col= color)
lines(x,SRR616853,type='l',col= color)
lines(x,SRR616854,type='l',col= color)
lines(x,SRR616855,type='l',col= color)
lines(x,SRR616856,type='l',col= color)
lines(x,SRR616857,type='l',col= color)
lines(x,SRR616858,type='l',col= color)
lines(x,SRR616859,type='l',col= color)
lines(x,SRR616860,type='l',col= color)
lines(x,SRR616861,type='l',col= color)
lines(x,SRR616862,type='l',col= color)
lines(x,SRR616863,type='l',col= color)
lines(x,SRR616864,type='l',col= color)
lines(x,SRR616865,type='l',col= color)
lines(x,SRR616866,type='l',col= color)
lines(x,SRR616867,type='l',col= color)
lines(x,SRR616868,type='l',col= color)
lines(x,SRR616869,type='l',col= color)
lines(x,SRR616870,type='l',col= color)
lines(x,SRR616871,type='l',col= color)
lines(x,SRR616872,type='l',col= color)
lines(x,SRR616873,type='l',col= color)
lines(x,SRR616874,type='l',col= color)
lines(x,SRR616875,type='l',col= color)
lines(x,SRR616876,type='l',col= color)
lines(x,SRR616877,type='l',col= color)
lines(x,SRR616878,type='l',col= color)
lines(x,SRR616879,type='l',col= color)
lines(x,SRR616880,type='l',col= color)
lines(x,SRR616881,type='l',col= color)
lines(x,SRR616882,type='l',col= color)
lines(x,SRR616883,type='l',col= color)
lines(x,SRR616884,type='l',col= color)
lines(x,SRR616885,type='l',col= color)
lines(x,SRR616886,type='l',col= color)
lines(x,SRR616887,type='l',col= color)
lines(x,SRR616888,type='l',col= color)
lines(x,SRR616889,type='l',col= color)
lines(x,SRR616890,type='l',col= color)
lines(x,SRR616891,type='l',col= color)
lines(x,SRR616892,type='l',col= color)
box(lty = "solid", col = 'black',lwd=3)
axis(side=1,lwd=2,lwd.ticks=4,col.ticks="black")
axis(side=2,lwd=3,lwd.ticks=4,col.ticks="black")
dev.off()
```


dev.off()

```

